version: 0.2

phases:

  pre_build:
    commands:
      - echo Iniciando sesion en Amazon ECR
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  build:
    commands:
      - echo Construyendo imagen Docker
      - docker build -t mi-aplicacion .

  post_build:
    commands:
      - echo Etiquetando imagen
      - docker tag mi-aplicacion:latest public.ecr.aws/t2h9w5f8/mi-aplicacion:latest
      - echo Subiendo imagen a ECR
      - docker push public.ecr.aws/t2h9w5f8/mi-aplicacion:latest
      - echo Imagen subida correctamente
